version: '2'

services:
  proxy:
    image: nginx
    container_name: nginx_proxy
    networks:
      - www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    restart: always

  gen:
    image: jwilder/docker-gen
    container_name: nginx_gen
    networks:
      - www
    command: -notify-sighup nginx_proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    restart: always
    depends_on:
      - proxy

  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_ssl
    networks:
      - www
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx_gen
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - gen
    
networks:
  www:
    external:
      name: www

