version: '2'

services:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    networks:
      - www
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx_gen
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - gen
